### ISSUE TITLE
Definición del proyecto

### ISSUE THREAD

**Issue by UntalivanCruz** [PrograMovil-1310/equipo1#1]

**Comment by UntalivanCruz** [comment]
@PrograMovil-1310/equipo1 por favor agregar una descripción del proyecto que desean crear en Flutter

**Comment by eduardolara16** [comment]
Probando

**Comment by zamirar31** [comment]
App para inventario de productos, que hace uso de la camara para escanear codigos de barra o QR.
La app mostrara:
-Log in page: Ingresar nombre y contraseña
-Dashboard page: muestra total de articulos en inventario, el valor de los articulos, articulos disponibles, asignados, perdidos y dañados.
-List page: muestra la lista de inventario y permite aplicar filtros.
-Asset page: muestra los datos de los articulos como numero de serie, fecha de compra, nombre del lugar de compra, estado del inventario y precio.
